Vagrant.configure("2") do |config|
  config.vm.define "testcsr1" do |testcsr1|
    testcsr1.vm.box = "iosxe/16.6.1"
    testcsr1.vm.network "forwarded_port", guest: 22, host: 2201
  end
  config.vm.define "testcsr2" do |testcsr2|
    testcsr2.vm.box = "iosxe/16.6.1"
    testcsr2.vm.network "forwarded_port", guest: 22, host: 2202
  end
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "main.yaml"
    ansible.inventory_path = "./dev"
    ansible.raw_arguments = ["--connection=paramiko"]
  end
end

